# -*- mode: python ; coding: utf-8 -*-
# PyInstaller v1.2.0 — dist/Availity_Automation_1.2.0.exe

a = Analysis(
    ['Availity_Automation.py'],
    pathex=[],
    binaries=[],
    datas=[('azbilling-new-logo.png', '.')],
    hiddenimports=[
        'availity_app',
        'availity_app.automation',
        'availity_app.constants',
        'availity_app.driver',
        'availity_app.logging_gui',
        'availity_app.resources',
        'availity_app.state',
        'availity_app.tk_ui',
        'availity_app.ui_control',
        'availity_app.utils',
        'availity_app.async_save',
        'availity_app.discovery_cache',
        'availity_app.resilience',
        'availity_app.search_grouping',
        'openpyxl',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Availity_Automation_1.2.0',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='azbilling-new-logo.ico',
)
